/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package voting;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import managecandidate.AddCandidateFrame;
import managecandidate.DeleteCandidateFrame;
import managecandidate.ViewCandidateFrame;
import managevoter.AddVoterDetailsFrame;
import managevoter.ViewVoterDetailsFrame;
import rcc.ReverseDecryptionHelper;
import rcc.ReverseEncryptionHelper;
import secure_evoting_0.Login_Frame;
import secure_evoting_0.UpdateAdminProfileFrame;

import userreg_otp.OTPGenSupporter;
import votecounting.Vote_Count_Frame;

/**
 *
 * @author welcome
 */
public class VotingFrame extends javax.swing.JFrame {

    /**
     * Creates new form VotingFrame
     */
    public String aadharcard,otp,votername;
  public String ekey="X134SY";
   public String dkey="X134SY";
    public VotingFrame() {
        super("Voting Frame");
        initComponents();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aadhar Card Number");

        jTextField1.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        jButton1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton1.setText("GO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Enter OTP");

        jTextField2.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N

        jButton2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton2.setText("Authenticate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                .addGap(59, 59, 59)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE))
                .addGap(71, 71, 71)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("jLabel3");

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Name 1");

        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 283, Short.MAX_VALUE)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(130, 130, 130))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(14, 14, 14))
            .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Name 2");

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(129, 129, 129))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addContainerGap(32, Short.MAX_VALUE))
            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Name 3");

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(125, 125, 125))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(20, Short.MAX_VALUE))
            .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Name 4");

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(122, 122, 122))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel7)
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.white, java.awt.Color.white));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Name 5");

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(124, 124, 124))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel8)
                .addContainerGap(23, Short.MAX_VALUE))
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(253, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(221, 221, 221))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jButton8.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jButton8.setText("Close Voting");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(222, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(205, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1390, 880);

        jMenu1.setText("Manage Profile");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/editprofile.png"))); // NOI18N
        jMenuItem1.setText("Edit Profile");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Manage Candidate");

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addcompany.png"))); // NOI18N
        jMenuItem2.setText("Add Candidate");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jMenuItem4.setText("View Candidate");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete1.png"))); // NOI18N
        jMenuItem5.setText("Delete Candidate");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Manage Voter");

        jMenuItem6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/addcompany.png"))); // NOI18N
        jMenuItem6.setText("Add Voter");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuItem7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jMenuItem7.setText("View Voter");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem7);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Vote");

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/start.png"))); // NOI18N
        jMenuItem3.setText("Start Voting");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/view.png"))); // NOI18N
        jMenuItem8.setText("View Vote");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem8);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Count");

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/count.png"))); // NOI18N
        jMenuItem9.setText("Count Vote");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem9);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Logout");

        jMenuItem10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout.png"))); // NOI18N
        jMenuItem10.setText("Exit");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem10);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
         aadharcard=jTextField1.getText();
        
          
       if(!isValidAadharCard(aadharcard))
              JOptionPane.showMessageDialog(null, "Please Enter Valid Aadhar Card Number");
       else
       { 
           
                otp=new OTPGenSupporter().getKey();
             System.out.println("OTP IS : "+otp);
             
         ArrayList data=new Name_EmailId_FetcherThroughAadhar().getDataRelatedAadhar(aadharcard);
         votername=(String)data.get(0);
         String email=(String)data.get(1);
//           
         
         String body="Dear Voter"+"\n Welcome To The Electronic Voting System"+"\n Please Use "+otp+" as OTP To Authenticate Your Vote";
         String sub="OTP For Voter Authentication";
         String to=email;
           JOptionPane.showMessageDialog(null, "OTP Is Sending On Regestered Email Id: "+ email);
           new SendMail().send(body, sub, to);
          
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        String otp1=jTextField2.getText();
        if(otp1.isEmpty())
            JOptionPane.showMessageDialog(null, "Please Enter OTP");
        else if(!otp.equals(otp1))
            JOptionPane.showMessageDialog(null, "Please Enter Valid OTP");
        else
        {
            jLabel3.setText(votername+" You Are Authenticated, Now You Can Cast Your Vote");
            
        jPanel3.setVisible(true);
         ArrayList data= new Constituency_Selection().getDataRelatedConstituency(Constituency_Frame.constituency);
         
          ArrayList row1=(ArrayList)data.get(0);
            String candidate_name1=(String)row1.get(0);
            jLabel4.setText(candidate_name1);
           byte  barr1[] = (byte[]) row1.get(1);
             ImageIcon icon1 = new ImageIcon(new ImageIcon(barr1).getImage().getScaledInstance(jButton3.getWidth(), jButton3.getHeight(), Image.SCALE_SMOOTH));
             jButton3.setIcon(icon1);
             
             
            ArrayList row2=(ArrayList)data.get(1);
            String candidate_name2=(String)row2.get(0);
            jLabel5.setText(candidate_name2);
            byte  barr2[] = (byte[]) row2.get(1);
             ImageIcon icon2 = new ImageIcon(new ImageIcon(barr2).getImage().getScaledInstance(jButton4.getWidth(), jButton4.getHeight(), Image.SCALE_SMOOTH));
             jButton4.setIcon(icon2);
             
             
              ArrayList row3=(ArrayList)data.get(2);
            String candidate_name3=(String)row3.get(0);
            jLabel6.setText(candidate_name3);
            byte  barr3[] = (byte[]) row3.get(1);
             ImageIcon icon3 = new ImageIcon(new ImageIcon(barr3).getImage().getScaledInstance(jButton5.getWidth(), jButton5.getHeight(), Image.SCALE_SMOOTH));
             jButton5.setIcon(icon3);
             
             
             
              ArrayList row4=(ArrayList)data.get(3);
            String candidate_name4=(String)row4.get(0);
            jLabel7.setText(candidate_name4);
            byte  barr4[] = (byte[]) row4.get(1);
             ImageIcon icon4 = new ImageIcon(new ImageIcon(barr4).getImage().getScaledInstance(jButton6.getWidth(), jButton6.getHeight(), Image.SCALE_SMOOTH));
             jButton6.setIcon(icon4);
             
             
              ArrayList row5=(ArrayList)data.get(4);
            String candidate_name5=(String)row5.get(0);
            jLabel8.setText(candidate_name5);
            byte  barr5[] = (byte[]) row5.get(1);
             ImageIcon icon5 = new ImageIcon(new ImageIcon(barr5).getImage().getScaledInstance(jButton7.getWidth(), jButton7.getHeight(), Image.SCALE_SMOOTH));
             jButton7.setIcon(icon5);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        
        String srno=new Serial_Number().getSerialNumber();
       
        DateAndTime dt = new DateAndTime();
        String date = dt.getDate();
        String time = dt.getTime();
        String sdt = date + " , " + time;
        
        String candidatename=jLabel4.getText();
        
        String partyname=new PartyNameFetcher().getPartyName(candidatename);
       
        int sr_no=Integer.parseInt(srno);
        sr_no=sr_no+1;
        String increasedsrno=Integer.toString(sr_no);
        System.out.println("Increasd srno:"+increasedsrno);
        
        System.out.println("Original values Before Encryption:");
        System.out.println(aadharcard+" , "+votername+" , "+Constituency_Frame.constituency+" , "+candidatename+" , "+partyname+" , "+sdt);
        
        ReverseEncryptionHelper reh=new ReverseEncryptionHelper();
       // String srno1=reh.startEncryption(increasedsrno, ekey);
        aadharcard=reh.startEncryption(aadharcard, ekey);
        votername=reh.startEncryption(votername, ekey);
        String constituency=reh.startEncryption(Constituency_Frame.constituency, ekey);
        candidatename=reh.startEncryption(candidatename, ekey);
        partyname=reh.startEncryption(partyname, ekey);
        sdt=reh.startEncryption(sdt, ekey);
        
       //  String bigenc=reh.startEncryption(srno, ekey);
        System.out.println(" values after Encryption:");
        System.out.println(aadharcard+" , "+votername+" , "+constituency+" , "+candidatename+" , "+partyname+" , "+sdt);
        
        String data=increasedsrno+aadharcard+votername+constituency+candidatename+partyname+sdt;
        
         Vote_Insertion vi=new Vote_Insertion();
         
        if(srno.equals("0"))
        {
             String hash = new MD5Hash().MDfive(data);
             char ch1=hash.charAt(0);
             char ch2=hash.charAt(5);
             char ch3=hash.charAt(11);
             char ch4=hash.charAt(14);
             char ch5=hash.charAt(23);
             char ch6=hash.charAt(26);
            
             String hashstr=Character.toString(ch1)+Character.toString(ch2)+Character.toString(ch3)+Character.toString(ch4)+Character.toString(ch5)+Character.toString(ch6);
             
             if(vi.isInsert(increasedsrno, aadharcard, votername, constituency, candidatename, partyname, sdt, hashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting Process");
        }
        else
        {
           // int big = new BigSerialNumber().getBigSno();
         //   String bigno=Integer.toString(big);
           // String bigsrno=new ReverseDecryptionHelper().startDecryption(bigno, dkey);
            
            System.out.println("Reached in else ======================");
            String blockhead = new Block_Head_Key_Fetcher().getBlockHeadKey(srno);
            String text1=data + blockhead;
            
            String hash1 = new MD5Hash().MDfive(text1);
            char nch1=hash1.charAt(0);
             char nch2=hash1.charAt(5);
             char nch3=hash1.charAt(11);
             char nch4=hash1.charAt(14);
             char nch5=hash1.charAt(23);
             char nch6=hash1.charAt(26);
            
             String nhashstr=Character.toString(nch1)+Character.toString(nch2)+Character.toString(nch3)+Character.toString(nch4)+Character.toString(nch5)+Character.toString(nch6);
            // int nbigno=Integer.parseInt(bigno);
          //  String nsrno=Integer.toString(nbigno+1);
           //  String nsrno=reh.startEncryption(increasedsrno, ekey);
              if(vi.isInsert(increasedsrno, aadharcard, votername,constituency, candidatename, partyname, sdt, nhashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         String srno=new Serial_Number().getSerialNumber();
      
        DateAndTime dt = new DateAndTime();
        String date = dt.getDate();
        String time = dt.getTime();
        String sdt = date + " , " + time;
        
        String candidatename=jLabel5.getText();
        
        String partyname=new PartyNameFetcher().getPartyName(candidatename);
      
         int sr_no=Integer.parseInt(srno);
        sr_no=sr_no+1;
        String increasedsrno=Integer.toString(sr_no);
        System.out.println("Increasd srno:"+increasedsrno);
        
        
      ReverseEncryptionHelper reh=new ReverseEncryptionHelper();
       // String srno1=reh.startEncryption(srno, ekey);
        aadharcard=reh.startEncryption(aadharcard, ekey);
        votername=reh.startEncryption(votername, ekey);
        String constituency=reh.startEncryption(Constituency_Frame.constituency, ekey);
        candidatename=reh.startEncryption(candidatename, ekey);
        partyname=reh.startEncryption(partyname, ekey);
        sdt=reh.startEncryption(sdt, ekey);
         
          String data=increasedsrno+aadharcard+votername+constituency+candidatename+partyname+sdt;
        
         Vote_Insertion vi=new Vote_Insertion();
         
        if(srno.equals("0"))
        {
             String hash = new MD5Hash().MDfive(data);
             char ch1=hash.charAt(0);
             char ch2=hash.charAt(5);
             char ch3=hash.charAt(11);
             char ch4=hash.charAt(14);
             char ch5=hash.charAt(23);
             char ch6=hash.charAt(26);
            
             String hashstr=Character.toString(ch1)+Character.toString(ch2)+Character.toString(ch3)+Character.toString(ch4)+Character.toString(ch5)+Character.toString(ch6);
             
             if(vi.isInsert(increasedsrno, aadharcard, votername, constituency, candidatename, partyname, sdt, hashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting Process");
        }
        else
        {
           
            String blockhead = new Block_Head_Key_Fetcher().getBlockHeadKey(srno);
            String text1=data + blockhead;
            
            String hash1 = new MD5Hash().MDfive(text1);
            char nch1=hash1.charAt(0);
             char nch2=hash1.charAt(5);
             char nch3=hash1.charAt(11);
             char nch4=hash1.charAt(14);
             char nch5=hash1.charAt(23);
             char nch6=hash1.charAt(26);
            
             String nhashstr=Character.toString(nch1)+Character.toString(nch2)+Character.toString(nch3)+Character.toString(nch4)+Character.toString(nch5)+Character.toString(nch6);
             
            
              if(vi.isInsert(increasedsrno, aadharcard, votername, constituency, candidatename, partyname, sdt, nhashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting Process");
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
         String srno=new Serial_Number().getSerialNumber();
       // String serialno=Integer.toString(srno);
        DateAndTime dt = new DateAndTime();
        String date = dt.getDate();
        String time = dt.getTime();
        String sdt = date + " , " + time;
        
        String candidatename=jLabel6.getText();
        
        String partyname=new PartyNameFetcher().getPartyName(candidatename);
       int sr_no=Integer.parseInt(srno);
        sr_no=sr_no+1;
        String increasedsrno=Integer.toString(sr_no);
        System.out.println("Increasd srno:"+increasedsrno);
 
        
        ReverseEncryptionHelper reh=new ReverseEncryptionHelper();
       // String srno1=reh.startEncryption(srno, ekey);
        aadharcard=reh.startEncryption(aadharcard, ekey);
        votername=reh.startEncryption(votername, ekey);
        String constituency=reh.startEncryption(Constituency_Frame.constituency, ekey);
        candidatename=reh.startEncryption(candidatename, ekey);
        partyname=reh.startEncryption(partyname, ekey);
        sdt=reh.startEncryption(sdt, ekey);
         
          String data=increasedsrno+aadharcard+votername+constituency+candidatename+partyname+sdt;
         
         Vote_Insertion vi=new Vote_Insertion();
         
        if(srno.equals("0"))
        {
             String hash = new MD5Hash().MDfive(data);
             char ch1=hash.charAt(0);
             char ch2=hash.charAt(5);
             char ch3=hash.charAt(11);
             char ch4=hash.charAt(14);
             char ch5=hash.charAt(23);
             char ch6=hash.charAt(26);
            
             String hashstr=Character.toString(ch1)+Character.toString(ch2)+Character.toString(ch3)+Character.toString(ch4)+Character.toString(ch5)+Character.toString(ch6);
             
             if(vi.isInsert(increasedsrno, aadharcard, votername,constituency, candidatename, partyname, sdt, hashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting Process");
        }
        else
        {
            
            String blockhead = new Block_Head_Key_Fetcher().getBlockHeadKey(srno);
            String text1=data + blockhead;
            
            String hash1 = new MD5Hash().MDfive(text1);
            char nch1=hash1.charAt(0);
             char nch2=hash1.charAt(5);
             char nch3=hash1.charAt(11);
             char nch4=hash1.charAt(14);
             char nch5=hash1.charAt(23);
             char nch6=hash1.charAt(26);
            
             String nhashstr=Character.toString(nch1)+Character.toString(nch2)+Character.toString(nch3)+Character.toString(nch4)+Character.toString(nch5)+Character.toString(nch6);
             
            
              if(vi.isInsert(increasedsrno, aadharcard, votername, constituency, candidatename, partyname, sdt, nhashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting Process");
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
         String srno=new Serial_Number().getSerialNumber();
      //  String serialno=Integer.toString(srno);
        DateAndTime dt = new DateAndTime();
        String date = dt.getDate();
        String time = dt.getTime();
        String sdt = date + " , " + time;
        
        String candidatename=jLabel7.getText();
        
        String partyname=new PartyNameFetcher().getPartyName(candidatename);
     int sr_no=Integer.parseInt(srno);
        sr_no=sr_no+1;
        String increasedsrno=Integer.toString(sr_no);
        System.out.println("Increasd srno:"+increasedsrno);
        
       ReverseEncryptionHelper reh=new ReverseEncryptionHelper();
        String srno1=reh.startEncryption(srno, ekey);
        aadharcard=reh.startEncryption(aadharcard, ekey);
        votername=reh.startEncryption(votername, ekey);
        String constituency=reh.startEncryption(Constituency_Frame.constituency, ekey);
        candidatename=reh.startEncryption(candidatename, ekey);
        partyname=reh.startEncryption(partyname, ekey);
        sdt=reh.startEncryption(sdt, ekey);
         
          String data=increasedsrno+aadharcard+votername+constituency+candidatename+partyname+sdt;
         
         Vote_Insertion vi=new Vote_Insertion();
         
        if(srno.equals("0"))
        {
             String hash = new MD5Hash().MDfive(data);
             char ch1=hash.charAt(0);
             char ch2=hash.charAt(5);
             char ch3=hash.charAt(11);
             char ch4=hash.charAt(14);
             char ch5=hash.charAt(23);
             char ch6=hash.charAt(26);
            
             String hashstr=Character.toString(ch1)+Character.toString(ch2)+Character.toString(ch3)+Character.toString(ch4)+Character.toString(ch5)+Character.toString(ch6);
             
             if(vi.isInsert(increasedsrno, aadharcard, votername,constituency, candidatename, partyname, sdt, hashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting Process");
        }
        else
        {
           
            String blockhead = new Block_Head_Key_Fetcher().getBlockHeadKey(srno);
            String text1=data + blockhead;
            
            String hash1 = new MD5Hash().MDfive(text1);
            char nch1=hash1.charAt(0);
             char nch2=hash1.charAt(5);
             char nch3=hash1.charAt(11);
             char nch4=hash1.charAt(14);
             char nch5=hash1.charAt(23);
             char nch6=hash1.charAt(26);
            
             String nhashstr=Character.toString(nch1)+Character.toString(nch2)+Character.toString(nch3)+Character.toString(nch4)+Character.toString(nch5)+Character.toString(nch6);
             
            
              if(vi.isInsert(increasedsrno, aadharcard, votername, constituency, candidatename, partyname, sdt, nhashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting Process");
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        String srno=new Serial_Number().getSerialNumber();
     //   String serialno=Integer.toString(srno);
        DateAndTime dt = new DateAndTime();
        String date = dt.getDate();
        String time = dt.getTime();
        String sdt = date + " , " + time;
        
        String candidatename=jLabel8.getText();
        
        String partyname=new PartyNameFetcher().getPartyName(candidatename);
        
        int sr_no=Integer.parseInt(srno);
        sr_no=sr_no+1;
        String increasedsrno=Integer.toString(sr_no);
        System.out.println("Increasd srno:"+increasedsrno);
        
     ReverseEncryptionHelper reh=new ReverseEncryptionHelper();
       // String srno1=reh.startEncryption(srno, ekey);
        aadharcard=reh.startEncryption(aadharcard, ekey);
        votername=reh.startEncryption(votername, ekey);
        String constituency=reh.startEncryption(Constituency_Frame.constituency, ekey);
        candidatename=reh.startEncryption(candidatename, ekey);
        partyname=reh.startEncryption(partyname, ekey);
        sdt=reh.startEncryption(sdt, ekey);
         
          String data=increasedsrno+aadharcard+votername+constituency+candidatename+partyname+sdt;
         
         Vote_Insertion vi=new Vote_Insertion();
         
        if(srno.equals("0"))
        {
             String hash = new MD5Hash().MDfive(data);
             char ch1=hash.charAt(0);
             char ch2=hash.charAt(5);
             char ch3=hash.charAt(11);
             char ch4=hash.charAt(14);
             char ch5=hash.charAt(23);
             char ch6=hash.charAt(26);
            
             String hashstr=Character.toString(ch1)+Character.toString(ch2)+Character.toString(ch3)+Character.toString(ch4)+Character.toString(ch5)+Character.toString(ch6);
             
             if(vi.isInsert(increasedsrno, aadharcard, votername, constituency, candidatename, partyname, sdt, hashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting Process");
        }
        else
        {
          
            String blockhead = new Block_Head_Key_Fetcher().getBlockHeadKey(srno);
            String text1=data + blockhead;
            
            String hash1 = new MD5Hash().MDfive(text1);
            char nch1=hash1.charAt(0);
             char nch2=hash1.charAt(5);
             char nch3=hash1.charAt(11);
             char nch4=hash1.charAt(14);
             char nch5=hash1.charAt(23);
             char nch6=hash1.charAt(26);
            
             String nhashstr=Character.toString(nch1)+Character.toString(nch2)+Character.toString(nch3)+Character.toString(nch4)+Character.toString(nch5)+Character.toString(nch6);
             
           
              if(vi.isInsert(increasedsrno, aadharcard, votername, constituency, candidatename, partyname, sdt, nhashstr))
                 JOptionPane.showMessageDialog(null, "Voting Process Is Done");
             else
                 JOptionPane.showMessageDialog(null, "Error In Voting Process");
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ClosingMailFrame cmf=new ClosingMailFrame();
        cmf.setVisible(true);
        cmf.setSize(590, 300);
        
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        UpdateAdminProfileFrame uapf=new UpdateAdminProfileFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        uapf.setVisible(true);
        uapf.setSize(d);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        AddCandidateFrame acf=new AddCandidateFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        acf.setVisible(true);
        acf.setSize(d);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewCandidateFrame vcf=new ViewCandidateFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        vcf.setVisible(true);
        vcf.setSize(d);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        DeleteCandidateFrame dcf=new DeleteCandidateFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        dcf.setVisible(true);
        dcf.setSize(d);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        AddVoterDetailsFrame dcf=new AddVoterDetailsFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        dcf.setVisible(true);
        dcf.setSize(d);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:

        this.dispose();
        ViewVoterDetailsFrame dcf=new ViewVoterDetailsFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        dcf.setVisible(true);
        dcf.setSize(d);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        //this.dispose();
        Constituency_Frame cf=new Constituency_Frame();
        cf.setVisible(true);
        cf.setSize(400,200);

    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ViewVoteFrame vvf=new ViewVoteFrame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        vvf.setVisible(true);
        vvf.setSize(d);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Vote_Count_Frame vcf=new Vote_Count_Frame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        vcf.setVisible(true);
        vcf.setSize(d);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        Login_Frame lf=new Login_Frame();
        Dimension d=Toolkit.getDefaultToolkit().getScreenSize();
        lf.setVisible(true);
        lf.setSize(d);
    }//GEN-LAST:event_jMenuItem10ActionPerformed
    public boolean isValidAadharCard(String aadharcard)
    {
        boolean flag=false;
        if(!aadharcard.isEmpty())
        {
            if(aadharcard.length()==12)
            {
                try
                {
                    long num=Long.parseLong(aadharcard);
                    flag=true;
                }
                catch(Exception ex)
                {
                    System.out.println("Exception is: "+ex);
                }
            }
        }
        return flag;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VotingFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VotingFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public javax.swing.JButton jButton3;
    public javax.swing.JButton jButton4;
    public javax.swing.JButton jButton5;
    public javax.swing.JButton jButton6;
    public javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    public javax.swing.JLabel jLabel4;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    public javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JPanel jPanel3;
    public javax.swing.JPanel jPanel4;
    public javax.swing.JPanel jPanel5;
    public javax.swing.JPanel jPanel6;
    public javax.swing.JPanel jPanel7;
    public javax.swing.JPanel jPanel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
